-- Matikan RLS sementara untuk tabel transaksi produksi dan turunannya
ALTER TABLE produksi_bahan DISABLE ROW LEVEL SECURITY;
ALTER TABLE produksi_packaging DISABLE ROW LEVEL SECURITY;
ALTER TABLE produksi_hasil DISABLE ROW LEVEL SECURITY;
ALTER TABLE stock_movements DISABLE ROW LEVEL SECURITY;
ALTER TABLE rate_borongan DISABLE ROW LEVEL SECURITY;
ALTER TABLE cash_flow DISABLE ROW LEVEL SECURITY;
ALTER TABLE biaya_operasional DISABLE ROW LEVEL SECURITY;
ALTER TABLE penjualan DISABLE ROW LEVEL SECURITY;
ALTER TABLE penjualan_detail DISABLE ROW LEVEL SECURITY;
